# Generated by Django 5.2 on 2025-07-25 17:31

import django.db.models.deletion
import proyectoapp.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, default='rut', max_length=12, validators=[proyectoapp.utils.validators.validate_rut])),
                ('empresa', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, default='nombre', max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa_logos/')),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='fondo/')),
                ('formulario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario.tipoformulario')),
                ('theme', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme')),
            ],
        ),
    ]
