# Generated by Django 5.2.5 on 2025-08-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria_operativa',
            field=models.CharField(choices=[('FUND_PUDAHUEL', 'Fundación Pudahuel'), ('FUND_CERRO', 'Fundación Cerro Navia'), ('GAE', 'GAE'), ('SP', 'SP'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='max_sedes_activas_por_persona',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='permite_concurrencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Sociedad de Responsabilidad Limitada'), ('SPA', 'Sociedad por Acciones'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada'), ('FUNDACION', 'Fundación'), ('COOP', 'Cooperativa'), ('OTRO', 'Otro')], default='SPA', max_length=12),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sedes_permitidas',
            field=models.ManyToManyField(related_name='empresas', to='institucion.sede'),
        ),
        migrations.CreateModel(
            name='EmpresaPersonaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_multisede', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_config', to='institucion.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('persona', 'empresa'), name='uniq_persona_empresa_cfg')],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='institucion.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='institucion.sede')),
            ],
            options={
                'indexes': [models.Index(fields=['persona', 'empresa', 'sede', 'fecha_inicio'], name='institucion_persona_bb3e0d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='asig_fechas_validas')],
            },
        ),
    ]
