# Generated by Django 5.2.5 on 2025-08-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_sede_empresa_categoria_operativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='cargo',
        ),
    ]
