# Generated by Django 5.2.5 on 2025-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_remove_asignacion_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_inicio',
            field=models.DateField(editable=False),
        ),
    ]
