# Generated by Django 5.2.5 on 2025-09-01 15:03

import django.db.models.deletion
import proyectoapp.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_initial'),
        ('institucion', '0004_alter_asignacion_fecha_inicio'),
        ('theme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=20, unique=True)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[proyectoapp.utils.validators.validate_rut])),
                ('tipo_empresa', models.CharField(choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Sociedad de Responsabilidad Limitada'), ('SPA', 'Sociedad por Acciones'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada'), ('COOP', 'Cooperativa'), ('OTRO', 'Otro')], default='SPA', max_length=12)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('permite_asignacion_multiple', models.BooleanField(default=False)),
                ('max_organizaciones_simultaneas', models.PositiveSmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa de Servicio',
                'verbose_name_plural': 'Empresas de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Organización',
                'verbose_name_plural': 'Tipos de Organización',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=20, unique=True)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[proyectoapp.utils.validators.validate_rut])),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizacion_logos/')),
                ('activa', models.BooleanField(default=True)),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='fondo/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario.tipoformulario')),
                ('theme', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institucion.tipoorganizacion')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SedeOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='institucion.organizacion')),
            ],
            options={
                'verbose_name': 'Sede de Organización',
                'verbose_name_plural': 'Sedes de Organización',
                'ordering': ['organizacion__nombre', 'nombre'],
                'unique_together': {('organizacion', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContratoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado'), ('RENOVACION', 'En Renovación')], default='ACTIVO', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='institucion.empresaservicio')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_servicio', to='institucion.organizacion')),
                ('sedes_permitidas', models.ManyToManyField(related_name='contratos_servicio', to='institucion.sedeorganizacion')),
            ],
            options={
                'verbose_name': 'Contrato de Servicio',
                'verbose_name_plural': 'Contratos de Servicio',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('empresa_servicio', 'organizacion', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asignacion', models.CharField(choices=[('FIJO', 'Asignación Fija'), ('VARIABLE', 'Asignación Variable'), ('TEMPORAL', 'Asignación Temporal'), ('PROYECTO', 'Por Proyecto')], default='FIJO', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('porcentaje_tiempo', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje de tiempo dedicado a esta asignación', max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_trabajo', to=settings.AUTH_USER_MODEL)),
                ('contrato_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.contratoservicio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_trabajo', to='institucion.sedeorganizacion')),
            ],
            options={
                'verbose_name': 'Asignación de Trabajador',
                'verbose_name_plural': 'Asignaciones de Trabajadores',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['trabajador', 'fecha_inicio', 'fecha_fin'], name='institucion_trabaja_8829a9_idx'), models.Index(fields=['contrato_servicio', 'sede', 'fecha_inicio'], name='institucion_contrat_93103e_idx'), models.Index(fields=['estado', 'fecha_inicio'], name='institucion_estado_12f653_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='asignacion_fechas_validas'), models.CheckConstraint(condition=models.Q(('porcentaje_tiempo__gte', 0), ('porcentaje_tiempo__lte', 100)), name='porcentaje_valido')],
            },
        ),
    ]
