# Generated by Django 5.2.5 on 2025-09-01 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0005_empresaservicio_tipoorganizacion_organizacion_and_more'),
        ('theme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignaciontrabajador',
            options={'verbose_name': 'Asignación de Trabajador', 'verbose_name_plural': 'Asignaciones de Trabajador'},
        ),
        migrations.AlterModelOptions(
            name='contratoservicio',
            options={'verbose_name': 'Contrato de Servicio', 'verbose_name_plural': 'Contratos de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='empresaservicio',
            options={'verbose_name': 'Empresa de Servicio', 'verbose_name_plural': 'Empresas de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='sedeorganizacion',
            options={'verbose_name': 'Sede de Organización', 'verbose_name_plural': 'Sedes de Organización'},
        ),
        migrations.RemoveConstraint(
            model_name='asignaciontrabajador',
            name='porcentaje_valido',
        ),
        migrations.RemoveIndex(
            model_name='asignaciontrabajador',
            name='institucion_contrat_93103e_idx',
        ),
        migrations.RemoveIndex(
            model_name='asignaciontrabajador',
            name='institucion_estado_12f653_idx',
        ),
        migrations.RenameField(
            model_name='asignaciontrabajador',
            old_name='actualizado_en',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='asignaciontrabajador',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='empresaservicio',
            old_name='max_organizaciones_simultaneas',
            new_name='max_sedes_por_trabajador',
        ),
        migrations.RenameField(
            model_name='empresaservicio',
            old_name='permite_asignacion_multiple',
            new_name='permite_asignaciones_multiples',
        ),
        migrations.RenameField(
            model_name='organizacion',
            old_name='tipo',
            new_name='tipo_organizacion',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='tipo_asignacion',
        ),
        migrations.AlterUniqueTogether(
            name='contratoservicio',
            unique_together={('empresa_servicio', 'organizacion')},
        ),
        migrations.AlterUniqueTogether(
            name='sedeorganizacion',
            unique_together={('organizacion', 'nombre'), ('organizacion', 'slug')},
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='es_permanente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratoservicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratoservicio',
            name='permite_multisede',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asignaciontrabajador',
            name='porcentaje_tiempo',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='asignaciontrabajador',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.sedeorganizacion'),
        ),
        migrations.AlterField(
            model_name='asignaciontrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_nuevas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contratoservicio',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='institucion.organizacion'),
        ),
        migrations.AlterField(
            model_name='empresaservicio',
            name='tipo_empresa',
            field=models.CharField(choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Sociedad de Responsabilidad Limitada'), ('SPA', 'Sociedad por Acciones'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada'), ('OTRO', 'Otro')], default='SPA', max_length=12),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='organizacion_fondos/'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme'),
        ),
        migrations.AddIndex(
            model_name='asignaciontrabajador',
            index=models.Index(fields=['contrato_servicio', 'sede', 'activa'], name='institucion_contrat_2d5ff6_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignaciontrabajador',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_tiempo__gte', 0), ('porcentaje_tiempo__lte', 100)), name='asignacion_porcentaje_valido'),
        ),
        migrations.AddConstraint(
            model_name='contratoservicio',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='contrato_fechas_validas'),
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='sedeorganizacion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='sedeorganizacion',
            name='fecha_creacion',
        ),
    ]
