# Generated by Django 5.2.5 on 2025-09-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_initial'),
        ('institucion', '0006_alter_asignaciontrabajador_options_and_more'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaservicio',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa_servicio_fondos/'),
        ),
        migrations.AddField(
            model_name='empresaservicio',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario.tipoformulario'),
        ),
        migrations.AddField(
            model_name='empresaservicio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa_servicio_logos/'),
        ),
        migrations.AddField(
            model_name='empresaservicio',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme'),
        ),
    ]
