# Generated by Django 5.2.5 on 2025-09-01 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_empresaservicio_fondo_empresaservicio_formulario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relación de Servicio',
                'verbose_name_plural': 'Relaciones de Servicio',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contratoservicio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='empresa_servicio',
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='contratoservicio',
            name='sedes_permitidas',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='contrato_servicio',
        ),
        migrations.RemoveField(
            model_name='empresaservicio',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='empresaservicio',
            name='theme',
        ),
        migrations.RemoveIndex(
            model_name='asignaciontrabajador',
            name='institucion_contrat_2d5ff6_idx',
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo_empresa',
            field=models.CharField(choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Sociedad de Responsabilidad Limitada'), ('SPA', 'Sociedad por Acciones'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada'), ('FUNDACION', 'Fundación'), ('OTRO', 'Otro')], default='FUNDACION', max_length=12),
        ),
        migrations.AddField(
            model_name='tipoorganizacion',
            name='es_prestador_servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoorganizacion',
            name='max_sedes_por_trabajador',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tipoorganizacion',
            name='permite_multisede',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relacionservicio',
            name='empresa_servicio',
            field=models.ForeignKey(limit_choices_to={'tipo_organizacion__es_prestador_servicio': True}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestados', to='institucion.organizacion'),
        ),
        migrations.AddField(
            model_name='relacionservicio',
            name='organizacion_cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_organizacion__es_prestador_servicio': False}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_recibidos', to='institucion.organizacion'),
        ),
        migrations.AddField(
            model_name='relacionservicio',
            name='sedes_permitidas',
            field=models.ManyToManyField(related_name='relaciones_servicio', to='institucion.sedeorganizacion'),
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='relacion_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.relacionservicio'),
        ),
        migrations.AddIndex(
            model_name='asignaciontrabajador',
            index=models.Index(fields=['organizacion', 'sede', 'activa'], name='institucion_organiz_fea1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontrabajador',
            index=models.Index(fields=['relacion_servicio', 'sede', 'activa'], name='institucion_relacio_4b450b_idx'),
        ),
        migrations.DeleteModel(
            name='ContratoServicio',
        ),
        migrations.DeleteModel(
            name='EmpresaServicio',
        ),
        migrations.AddConstraint(
            model_name='relacionservicio',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='relacion_fechas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='relacionservicio',
            unique_together={('empresa_servicio', 'organizacion_cliente')},
        ),
    ]
