# Generated by Django 5.2.5 on 2025-09-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_initial'),
        ('institucion', '0008_relacionservicio_and_more'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='fondo',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='theme',
        ),
        migrations.AddField(
            model_name='sedeorganizacion',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='sede_fondos/'),
        ),
        migrations.AddField(
            model_name='sedeorganizacion',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario.tipoformulario'),
        ),
        migrations.AddField(
            model_name='sedeorganizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sede_logos/'),
        ),
        migrations.AddField(
            model_name='sedeorganizacion',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme'),
        ),
    ]
