# Generated by Django 5.2 on 2025-07-25 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_area', models.CharField(max_length=255)),
                ('ponderacion', models.IntegerField(default=0, help_text='Ponderación como porcentaje (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.CharField(max_length=7)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('completado', models.BooleanField(default=False)),
                ('text_destacar', models.TextField(blank=True, null=True)),
                ('text_mejorar', models.TextField(blank=True, null=True)),
                ('logro_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estructura_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.CharField(help_text='Formato: MM-AAAA (ejemplo: 06-2025)', max_length=7, verbose_name='Mes y Año de Auto Evaluación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignación Auto Evaluación',
                'verbose_name_plural': 'Asignaciones Auto Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.CharField(max_length=7)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('completado', models.BooleanField(default=False)),
                ('text_destacar', models.TextField(blank=True, null=True)),
                ('text_mejorar', models.TextField(blank=True, null=True)),
                ('logro_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estructura_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('indicador', models.TextField()),
                ('definicion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JefeEvaluacionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.CharField(max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asignación Evaluación',
                'verbose_name_plural': 'Asignaciones Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NivelLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nvl', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaIndicadorJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.IntegerField()),
                ('puntaje', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_tipo_evaluacion', models.CharField(max_length=255, unique=True)),
                ('auto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TipoEvaluacion',
                'verbose_name_plural': 'Tipo Evaluaciones',
            },
        ),
    ]
