# Generated by Django 5.2 on 2025-07-25 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoevaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencia',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='evaluacion.areaevaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacionasignada',
            name='personas_asignadas',
            field=models.ManyToManyField(related_name='auto_evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_que_he_realizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_como_evaluado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicador',
            name='competencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='evaluacion.competencia'),
        ),
        migrations.AddField(
            model_name='jefeevaluacionasignada',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_por_realizar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jefeevaluacionasignada',
            name='personas',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nivellogro',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nvlindicadores', to='evaluacion.indicador'),
        ),
        migrations.AddField(
            model_name='respuestaindicador',
            name='autoevaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.autoevaluacion'),
        ),
        migrations.AddField(
            model_name='respuestaindicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.indicador'),
        ),
        migrations.AddField(
            model_name='respuestaindicadorjefe',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.evaluacionjefe'),
        ),
        migrations.AddField(
            model_name='jefeevaluacionasignada',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.tipoevaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.tipoevaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacionasignada',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='evaluacion.tipoevaluacion'),
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.tipoevaluacion'),
        ),
        migrations.AddField(
            model_name='areaevaluacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='evaluacion.tipoevaluacion'),
        ),
    ]
