# Generated by Django 5.2.5 on 2025-08-21 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_alter_indicador_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionjefe',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autoevaluacion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoevaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionjefe',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_como_evaluado', to=settings.AUTH_USER_MODEL),
        ),
    ]
