# Generated by Django 5.2.5 on 2025-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_autoevaluacion_ponderada_evaluacionjefe_ponderada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoevaluacion',
            name='ponderada',
            field=models.BooleanField(default=False),
        ),
    ]
