# Generated by Django 5.2.5 on 2025-08-27 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_tipoevaluacion_ponderada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefeevaluacionasignada',
            name='evaluador',
        ),
        migrations.RemoveField(
            model_name='jefeevaluacionasignada',
            name='personas',
        ),
        migrations.CreateModel(
            name='JefeEvaluacionAsignadaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='evaluacion.jefeevaluacionasignada')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalua_a', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['asignacion', 'persona'], name='evaluacion__asignac_962965_idx'), models.Index(fields=['evaluador'], name='evaluacion__evaluad_a0f606_idx')],
                'unique_together': {('asignacion', 'persona')},
            },
        ),
    ]
