# Generated by Django 5.2.5 on 2025-09-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_alter_jefeevaluacionasignadadetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionasignada',
            name='auto_tipo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_auto_pareadas', to='evaluacion.tipoevaluacion'),
        ),
    ]
