# Generated by Django 5.2.5 on 2025-09-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0011_alter_evaluacionasignada_auto_tipo_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluacion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoevaluaciones', to='evaluacion.evaluacionasignada'),
        ),
        migrations.AlterField(
            model_name='evaluacionasignada',
            name='auto_tipo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_auto_pareadas', to='evaluacion.tipoevaluacion'),
        ),
        migrations.AlterField(
            model_name='evaluacionjefe',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_jefatura', to='evaluacion.evaluacionasignada'),
        ),
    ]
