# Generated by Django 5.2.5 on 2025-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0012_alter_autoevaluacion_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaindicador',
            name='indicador',
            field=models.IntegerField(),
        ),
    ]
