# Generated by Django 5.2.5 on 2025-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0014_remove_autoevaluacion_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionjefe',
            name='retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
