# Generated by Django 5.2.5 on 2025-09-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0016_evaluacionjefe_cerrado_para_firma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionjefe',
            name='reunion_realizada',
        ),
    ]
