# Generated by Django 5.2.5 on 2025-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0019_alter_evaluacionjefe_estado_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoevaluacion',
            name='n_tipo_evaluacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='tipoevaluacion',
            constraint=models.UniqueConstraint(fields=('n_tipo_evaluacion', 'auto'), name='unique_nombre_por_tipo_evaluacion'),
        ),
    ]
