# Generated by Django 5.2 on 2025-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('primary_color', models.CharField(help_text='Color primario en formato HEX (ej: #2563eb)', max_length=7)),
                ('secondary_color', models.CharField(help_text='Color secundario en formato HEX', max_length=7)),
                ('third_color', models.CharField(blank=True, help_text='Color terciario en formato HEX', max_length=7, null=True)),
                ('background_from', models.CharField(help_text='Color inicial del degradado', max_length=7)),
                ('background_to', models.CharField(help_text='Color final del degradado', max_length=7)),
                ('background_from_dark', models.CharField(blank=True, help_text='Color inicial modo oscuro', max_length=7, null=True)),
                ('background_to_dark', models.CharField(blank=True, help_text='Color final modo oscuro', max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, help_text='Color de acento', max_length=7, null=True)),
                ('modo_oscuro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['name'],
            },
        ),
    ]
