# Generated by Django 5.2.5 on 2025-09-26 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
        ('theme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_nuevas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='theme',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='institucion.empresa'),
        ),
        migrations.AddField(
            model_name='empresapersonaconfig',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_config', to='institucion.empresa'),
        ),
        migrations.AddField(
            model_name='empresapersonaconfig',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.organizacion'),
        ),
        migrations.AddField(
            model_name='relacionservicio',
            name='empresa_servicio',
            field=models.ForeignKey(limit_choices_to={'tipo_organizacion__es_prestador_servicio': True}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestados', to='institucion.organizacion'),
        ),
        migrations.AddField(
            model_name='relacionservicio',
            name='organizacion_cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_organizacion__es_prestador_servicio': False}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_recibidos', to='institucion.organizacion'),
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='relacion_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.relacionservicio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sedes_permitidas',
            field=models.ManyToManyField(related_name='empresas', to='institucion.sede'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='institucion.sede'),
        ),
        migrations.AddField(
            model_name='sedeorganizacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='institucion.organizacion'),
        ),
        migrations.AddField(
            model_name='sedeorganizacion',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.theme'),
        ),
        migrations.AddField(
            model_name='relacionservicio',
            name='sedes_permitidas',
            field=models.ManyToManyField(related_name='relaciones_servicio', to='institucion.sedeorganizacion'),
        ),
        migrations.AddField(
            model_name='asignaciontrabajador',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='institucion.sedeorganizacion'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institucion.tipoorganizacion'),
        ),
        migrations.AddConstraint(
            model_name='empresapersonaconfig',
            constraint=models.UniqueConstraint(fields=('persona', 'empresa'), name='uniq_persona_empresa_cfg'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['persona', 'empresa', 'sede', 'fecha_inicio'], name='institucion_persona_bb3e0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='asig_fechas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='sedeorganizacion',
            unique_together={('organizacion', 'nombre'), ('organizacion', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='relacionservicio',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='relacion_fechas_validas'),
        ),
        migrations.AlterUniqueTogether(
            name='relacionservicio',
            unique_together={('empresa_servicio', 'organizacion_cliente')},
        ),
        migrations.AddIndex(
            model_name='asignaciontrabajador',
            index=models.Index(fields=['trabajador', 'fecha_inicio', 'fecha_fin'], name='institucion_trabaja_8829a9_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontrabajador',
            index=models.Index(fields=['organizacion', 'sede', 'activa'], name='institucion_organiz_fea1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontrabajador',
            index=models.Index(fields=['relacion_servicio', 'sede', 'activa'], name='institucion_relacio_4b450b_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignaciontrabajador',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='asignacion_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='asignaciontrabajador',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_tiempo__gte', 0), ('porcentaje_tiempo__lte', 100)), name='asignacion_porcentaje_valido'),
        ),
    ]
