# Generated by Django 5.2.5 on 2025-11-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='max_sedes_activas_por_persona',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='permite_concurrencia',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='sedes_permitidas',
        ),
    ]
