# Generated by Django 5.2.5 on 2025-08-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_initial'),
    ]

    operations = [
    ]
