# Generated by Django 5.2.5 on 2025-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_rebuild_evaluacion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'ordering': ['numero']},
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.UniqueConstraint(fields=('competencias', 'numero'), name='uniq_indicador_numero_por_competencia'),
        ),
    ]
