# Generated by Django 5.2.5 on 2025-08-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_evaluacionjefe_firmado_alter_autoevaluacion_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluacion',
            name='ponderada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='ponderada',
            field=models.BooleanField(default=False),
        ),
    ]
