# Generated by Django 5.2.5 on 2025-08-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_remove_jefeevaluacionasignada_evaluador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluacion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoevaluaciones', to='evaluacion.evaluacionasignada'),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_jefatura', to='evaluacion.evaluacionasignada'),
        ),
        migrations.AlterField(
            model_name='jefeevaluacionasignadadetalle',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_eval_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jefeevaluacionasignadadetalle',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_eval_persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='autoevaluacion',
            constraint=models.UniqueConstraint(fields=('persona', 'tipo_evaluacion', 'fecha_evaluacion'), name='uniq_auto_persona_tipo_fecha'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionjefe',
            constraint=models.UniqueConstraint(fields=('persona', 'tipo_evaluacion', 'fecha_evaluacion', 'evaluador'), name='uniq_jefe_persona_tipo_fecha_eval'),
        ),
    ]
