# Generated by Django 5.2.5 on 2025-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0013_alter_respuestaindicador_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoevaluacion',
            name='asignacion',
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='version_plantilla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='version_plantilla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuestaindicador',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='respuestaindicador',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='respuestaindicador',
            constraint=models.UniqueConstraint(fields=('autoevaluacion', 'indicador'), name='uniq_autoeval_indicador'),
        ),
    ]
