# Generated by Django 5.2.5 on 2025-09-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0017_remove_evaluacionjefe_reunion_realizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionjefe',
            name='firmado',
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='estado_firma',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('denegado', 'Denegado')], default='pendiente', help_text='Estado de la firma: pendiente, firmado o denegado', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='motivo_denegacion',
            field=models.TextField(blank=True, help_text='Motivo por el cual se denegó la evaluación', null=True),
        ),
    ]
