# Generated by Django 5.2.5 on 2025-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0018_remove_evaluacionjefe_firmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionjefe',
            name='estado_firma',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('firmado_obs', 'Firmado con Observaciones')], default='pendiente', help_text='Estado de la firma: pendiente, firmado o firmado_obs', max_length=20),
        ),
    ]
