# Generated by Django 5.2.5 on 2025-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_accesspermission_empresa_accesspermission_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspermission',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='accesspermission',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
