# Generated by Django 5.2.5 on 2025-11-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0005_accesspermission_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspermission',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='accesspermission',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Super usuario'),
        ),
    ]
