# Generated by Django 5.2.5 on 2025-08-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_autoevaluacion_asignacion_evaluacionjefe_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jefeevaluacionasignadadetalle',
            options={'ordering': ['asignacion_id', 'persona_id']},
        ),

        # 🔽 Reemplaza el AlterUniqueTogether por esto:
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='jefeevaluacionasignadadetalle',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),

        migrations.AddField(
            model_name='evaluacionasignada',
            name='auto_tipo_evaluacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='asignaciones_auto_pareadas',
                to='evaluacion.tipoevaluacion',
            ),
        ),
        migrations.AddConstraint(
            model_name='jefeevaluacionasignadadetalle',
            constraint=models.UniqueConstraint(
                fields=('asignacion', 'persona'),
                name='uniq_jefe_asignacion_persona',
            ),
        ),
        migrations.AddConstraint(
            model_name='jefeevaluacionasignadadetalle',
            constraint=models.CheckConstraint(
                condition=models.Q(('persona', models.F('evaluador')), _negated=True),
                name='chk_persona_distinta_de_evaluador',
            ),
        ),
    ]
