# Generated by Django 5.2.5 on 2025-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0015_evaluacionjefe_retroalimentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionjefe',
            name='cerrado_para_firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='fecha_reunion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='retroalimentacion_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacionjefe',
            name='reunion_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
