# Generated by Django 5.2 on 2025-07-25 17:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import proyectoapp.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institucion', '0001_initial'),
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitación',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TituloCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
            },
        ),
        migrations.CreateModel(
            name='Tramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tramo',
                'verbose_name_plural': 'Tramos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('password', models.CharField(default='1320', editable=False, max_length=100, verbose_name='contraseña')),
                ('rut', models.CharField(max_length=12, null=True, validators=[proyectoapp.utils.validators.validate_rut])),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='usuario')),
                ('first_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super usuario')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='cumpleanio')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Ingreso')),
                ('tiempo', models.FloatField(blank=True, default=None, null=True, verbose_name='días en la empresa')),
                ('tiempo_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='tiempo en formato legible')),
                ('d_ini', models.FloatField(default=0, verbose_name='Cantidad Inicial')),
                ('observacion_dia', models.TextField(blank=True, null=True, verbose_name='Observación Día')),
                ('dias_tomados', models.FloatField(default=0, verbose_name='Días Tomados')),
                ('dias_restantes', models.FloatField(default=2, verbose_name='Días Restantes')),
                ('dias_cumpleanios', models.FloatField(default=1, verbose_name='Días cumpleanios')),
                ('cumpleanio_ocupado', models.FloatField(default=0, verbose_name='Días cumpleanios ocupado')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institucion.empresa')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='auth.group', verbose_name='grupo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL, verbose_name='jefe')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.cargo')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.ciclo')),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.codigo')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.genero')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del contacto')),
                ('telefono', models.CharField(max_length=120, verbose_name='Teléfono')),
                ('parentezco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje obtenido en la evaluación', max_digits=5)),
                ('drive_url', models.URLField(blank=True, null=True)),
                ('anio', models.CharField(help_text='Año de evaluación, ej: 202407', max_length=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.IntegerField()),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='proyectoapp.capacitacion')),
                ('usuario', models.ManyToManyField(related_name='capacitaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación Capacitación',
                'verbose_name_plural': 'Participación Capacitación',
            },
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='titulo_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectoapp.titulocapacitacion'),
        ),
        migrations.CreateModel(
            name='UsuarioDiplomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('diplomado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulo.diplomado')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.institucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diplomado',
                'verbose_name_plural': 'Diplomado',
                'unique_together': {('usuario', 'diplomado')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='diplomados',
            field=models.ManyToManyField(blank=True, through='proyectoapp.UsuarioDiplomado', to='titulo.diplomado'),
        ),
        migrations.CreateModel(
            name='UsuarioMagister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.institucion')),
                ('magister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulo.magister')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magister',
                'verbose_name_plural': 'Magister',
                'unique_together': {('usuario', 'magister')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='magisters',
            field=models.ManyToManyField(blank=True, through='proyectoapp.UsuarioMagister', to='titulo.magister'),
        ),
        migrations.CreateModel(
            name='UsuarioTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulo.institucion')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulo.titulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
                'unique_together': {('usuario', 'titulo')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='titulos',
            field=models.ManyToManyField(blank=True, through='proyectoapp.UsuarioTitulo', to='titulo.titulo'),
        ),
        migrations.CreateModel(
            name='Bienios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienios', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoapp.tramos')),
            ],
            options={
                'verbose_name': 'Bienios',
                'verbose_name_plural': 'Bienios',
                'unique_together': {('usuario', 'bienios')},
            },
        ),
    ]
