# Generated by Django 5.2.5 on 2025-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0002_rename_cumpleaño_ocupado_user_cumpleanio_ocupado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tiempo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tiempo_en',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
    ]
