# Generated by Django 5.2.5 on 2025-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0003_remove_user_tiempo_remove_user_tiempo_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEF', 'Indefinido'), ('PLAZO', 'Plazo fijo')], default='INDEF', max_length=6),
        ),
    ]
