# Generated by Django 5.2.5 on 2025-08-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0004_user_fecha_termino_contrato_user_tipo_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fecha_salida',
        ),
    ]
