# Generated by Django 5.2.5 on 2025-08-30 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0005_remove_user_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha Ingreso'),
        ),
    ]
