# Generated by Django 5.2.5 on 2025-09-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_alter_asignaciontrabajador_options_and_more'),
        ('proyectoapp', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='DEPRECADO: Usar asignaciones_trabajo en su lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institucion.empresa'),
        ),
    ]
