# Generated by Django 5.2.5 on 2025-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoapp', '0007_alter_user_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulocapacitacion',
            options={'verbose_name': 'Titulo Capacitación', 'verbose_name_plural': 'Titulos Capacitación'},
        ),
    ]
