# Generated by Django 5.2.5 on 2025-09-24 12:18

import django.db.models.deletion
import proyectoapp.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institucion', '0009_mover_campos_visuales_a_sede'),
        ('proyectoapp', '0008_alter_titulocapacitacion_options'),
        ('titulo', '0002_alter_diplomado_diplomado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='anio',
            field=models.CharField(help_text='Año de evaluación, ej: 202407', max_length=6, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='drive_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Drive'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje obtenido en la evaluación', max_digits=5, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='cumpleaños'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.ciclo', verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.codigo', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cumpleanio_ocupado',
            field=models.FloatField(default=0, verbose_name='Días cumpleaños ocupado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dias_cumpleanios',
            field=models.FloatField(default=1, verbose_name='Días cumpleaños'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diplomados',
            field=models.ManyToManyField(blank=True, through='proyectoapp.UsuarioDiplomado', to='titulo.diplomado', verbose_name='Diplomados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='DEPRECADO: Usar asignaciones_trabajo en su lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institucion.empresa', verbose_name='Empresa (Deprecado)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha término contrato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoapp.genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='user',
            name='magisters',
            field=models.ManyToManyField(blank=True, through='proyectoapp.UsuarioMagister', to='titulo.magister', verbose_name='Magísteres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=12, null=True, validators=[proyectoapp.utils.validators.validate_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEF', 'Indefinido'), ('PLAZO', 'Plazo fijo')], default='INDEF', max_length=6, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='titulos',
            field=models.ManyToManyField(blank=True, through='proyectoapp.UsuarioTitulo', to='titulo.titulo', verbose_name='Títulos'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['usuario', 'anio'], name='proyectoapp_usuario_c1c213_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['fecha_creacion'], name='proyectoapp_fecha_c_a0f648_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rut'], name='proyectoapp_rut_bb3488_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='proyectoapp_email_ecfc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='proyectoapp_date_jo_d0c879_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tipo_contrato'], name='proyectoapp_tipo_co_f0e82d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='proyectoapp_is_acti_32fae9_idx'),
        ),
    ]
