# Generated by Django 5.2.5 on 2025-10-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoemergencia',
            name='usuario',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='usuarios_us_tipo_co_a9b793_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cumpleanio_ocupado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='d_ini',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dias_cumpleanios',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dias_restantes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dias_tomados',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_termino_contrato',
        ),
        migrations.RemoveField(
            model_name='user',
            name='observacion_dia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_contrato',
        ),
        migrations.DeleteModel(
            name='ContactoEmergencia',
        ),
    ]
