# Generated by Django 5.2.5 on 2025-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_contactoemergencia_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='fecha término contrato'),
        ),
    ]
