# Generated by Django 5.2.5 on 2025-10-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_tipo_contrato_alter_user_fecha_termino_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codigo',
        ),
        migrations.DeleteModel(
            name='Codigo',
        ),
    ]
