# Generated by Django 5.2.5 on 2025-09-26 23:11

import usuarios.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(editable=False)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_tiempo', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('es_permanente', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asignación de Trabajador',
                'verbose_name_plural': 'Asignaciones de Trabajador',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, default='rut', max_length=12, validators=[usuarios.utils.validators.validate_rut])),
                ('empresa', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, default='nombre', max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa_logos/')),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='fondo/')),
                ('tipo_empresa', models.CharField(choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Sociedad de Responsabilidad Limitada'), ('SPA', 'Sociedad por Acciones'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada'), ('FUNDACION', 'Fundación'), ('COOP', 'Cooperativa'), ('OTRO', 'Otro')], default='SPA', max_length=12)),
                ('categoria_operativa', models.CharField(choices=[('FUND_PUDAHUEL', 'Fundación Pudahuel'), ('FUND_CERRO', 'Fundación Cerro Navia'), ('GAE', 'GAE'), ('SP', 'SP'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('max_sedes_activas_por_persona', models.PositiveSmallIntegerField(default=1)),
                ('permite_concurrencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaPersonaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_multisede', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[usuarios.utils.validators.validate_rut])),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('tipo_empresa', models.CharField(choices=[('SA', 'Sociedad Anónima'), ('LTDA', 'Sociedad de Responsabilidad Limitada'), ('SPA', 'Sociedad por Acciones'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada'), ('FUNDACION', 'Fundación'), ('OTRO', 'Otro')], default='FUNDACION', max_length=12)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='RelacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relación de Servicio',
                'verbose_name_plural': 'Relaciones de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SedeOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sede_logos/')),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='sede_fondos/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sede de Organización',
                'verbose_name_plural': 'Sedes de Organización',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_prestador_servicio', models.BooleanField(default=False)),
                ('permite_multisede', models.BooleanField(default=False)),
                ('max_sedes_por_trabajador', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Organización',
                'verbose_name_plural': 'Tipos de Organización',
            },
        ),
    ]
