# Generated by Django 5.2.5 on 2025-11-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_remove_empresa_max_sedes_activas_por_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='relacion_servicio',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='asignaciontrabajador',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='empresapersonaconfig',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresapersonaconfig',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='tipo_organizacion',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='relacionservicio',
                    unique_together=None,
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='relacionservicio',
            name='organizacion_cliente',
        ),
        migrations.RemoveField(
            model_name='relacionservicio',
            name='empresa_servicio',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='sedeorganizacion',
                    unique_together=None,
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='sedeorganizacion',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='relacionservicio',
            name='sedes_permitidas',
        ),
        
        migrations.RemoveField(
            model_name='sedeorganizacion',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='categoria_operativa',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='AsignacionTrabajador',
        ),
        migrations.DeleteModel(
            name='EmpresaPersonaConfig',
        ),
        migrations.DeleteModel(
            name='TipoOrganizacion',
        ),
        migrations.DeleteModel(
            name='Organizacion',
        ),
        migrations.DeleteModel(
            name='RelacionServicio',
        ),
        migrations.DeleteModel(
            name='SedeOrganizacion',
        ),
    ]
