# Generated by Django 5.2.5 on 2025-09-26 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='empresa',
            field=models.ManyToManyField(blank=True, to='institucion.empresa'),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='templates',
            field=models.ManyToManyField(related_name='permissions', to='acceso.templateaccess'),
        ),
    ]
