# Generated by Django 5.2.5 on 2025-11-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_remove_accesspermission_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='super usuario'),
        ),
    ]
