# Generated by Django 5.2.5 on 2025-11-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0004_accesspermission_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspermission',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='personal'),
        ),
    ]
