# Generated by Django 5.2.5 on 2025-10-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institucion', '0002_initial'),
        ('usuarios', '0003_user_fecha_termino_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEF', 'Indefinido'), ('PLAZO', 'Plazo fijo')], default='INDEF', max_length=6, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha término contrato'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tipo_contrato'], name='usuarios_us_tipo_co_a9b793_idx'),
        ),
    ]
