# Generated by Django 5.2.5 on 2025-11-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_remove_accesspermission_titulo_and_more'),
        ('institucion', '0004_remove_asignaciontrabajador_organizacion_and_more'),
        ('usuarios', '0005_remove_user_codigo_delete_codigo'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE usuarios_user SET group_id = NULL "
                "WHERE group_id IS NOT NULL "
                "AND group_id NOT IN (SELECT id FROM acceso_accesspermission);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institucion.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='acceso.accesspermission', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
