from decouple import config

FRONTEND_URL = config('FRONTEND_URL')  # Ej. https://app.gsr.cat/

LOGIN_URL = FRONTEND_URL + "/login"
LOGIN_REDIRECT_URL = FRONTEND_URL
LOGOUT_REDIRECT_URL = FRONTEND_URL + "/login?logged_out=true"

ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = False
ACCOUNT_LOGOUT_REDIRECT_URL = LOGOUT_REDIRECT_URL
ACCOUNT_LOGIN_REDIRECT_URL = LOGIN_REDIRECT_URL
